targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: socfony|lib/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: socfony|lib/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: socfony|lib/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: socfony|lib/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
